# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vault_pb2 as vault__pb2


class PasswordVaultStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StorePassword = channel.unary_unary(
                '/vault.PasswordVault/StorePassword',
                request_serializer=vault__pb2.StoreRequest.SerializeToString,
                response_deserializer=vault__pb2.StoreResponse.FromString,
                )
        self.RetrievePassword = channel.unary_unary(
                '/vault.PasswordVault/RetrievePassword',
                request_serializer=vault__pb2.RetrieveRequest.SerializeToString,
                response_deserializer=vault__pb2.RetrieveResponse.FromString,
                )
        self.Register = channel.unary_unary(
                '/vault.PasswordVault/Register',
                request_serializer=vault__pb2.UserRequest.SerializeToString,
                response_deserializer=vault__pb2.UserResponse.FromString,
                )
        self.Login = channel.unary_unary(
                '/vault.PasswordVault/Login',
                request_serializer=vault__pb2.UserRequest.SerializeToString,
                response_deserializer=vault__pb2.UserResponse.FromString,
                )
        self.SearchUsersByName = channel.unary_unary(
                '/vault.PasswordVault/SearchUsersByName',
                request_serializer=vault__pb2.SearchRequest.SerializeToString,
                response_deserializer=vault__pb2.SearchResponse.FromString,
                )


class PasswordVaultServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StorePassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrievePassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchUsersByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PasswordVaultServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StorePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.StorePassword,
                    request_deserializer=vault__pb2.StoreRequest.FromString,
                    response_serializer=vault__pb2.StoreResponse.SerializeToString,
            ),
            'RetrievePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrievePassword,
                    request_deserializer=vault__pb2.RetrieveRequest.FromString,
                    response_serializer=vault__pb2.RetrieveResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=vault__pb2.UserRequest.FromString,
                    response_serializer=vault__pb2.UserResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=vault__pb2.UserRequest.FromString,
                    response_serializer=vault__pb2.UserResponse.SerializeToString,
            ),
            'SearchUsersByName': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchUsersByName,
                    request_deserializer=vault__pb2.SearchRequest.FromString,
                    response_serializer=vault__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vault.PasswordVault', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PasswordVault(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StorePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vault.PasswordVault/StorePassword',
            vault__pb2.StoreRequest.SerializeToString,
            vault__pb2.StoreResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrievePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vault.PasswordVault/RetrievePassword',
            vault__pb2.RetrieveRequest.SerializeToString,
            vault__pb2.RetrieveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vault.PasswordVault/Register',
            vault__pb2.UserRequest.SerializeToString,
            vault__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vault.PasswordVault/Login',
            vault__pb2.UserRequest.SerializeToString,
            vault__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchUsersByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vault.PasswordVault/SearchUsersByName',
            vault__pb2.SearchRequest.SerializeToString,
            vault__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
