# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vault.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvault.proto\x12\x05vault\">\n\x0cStoreRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"\x1f\n\rStoreResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\" \n\x0fRetrieveRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x7f\n\x10RetrieveResponse\x12\x39\n\tpasswords\x18\x01 \x03(\x0b\x32&.vault.RetrieveResponse.PasswordsEntry\x1a\x30\n\x0ePasswordsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"8\n\x0bUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x17\n\x0fmaster_password\x18\x02 \x01(\t\"/\n\x0cUserResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1d\n\rSearchRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x0eSearchResponse\x12\x11\n\tusernames\x18\x01 \x03(\t2\xb9\x02\n\rPasswordVault\x12:\n\rStorePassword\x12\x13.vault.StoreRequest\x1a\x14.vault.StoreResponse\x12\x43\n\x10RetrievePassword\x12\x16.vault.RetrieveRequest\x1a\x17.vault.RetrieveResponse\x12\x33\n\x08Register\x12\x12.vault.UserRequest\x1a\x13.vault.UserResponse\x12\x30\n\x05Login\x12\x12.vault.UserRequest\x1a\x13.vault.UserResponse\x12@\n\x11SearchUsersByName\x12\x14.vault.SearchRequest\x1a\x15.vault.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vault_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RETRIEVERESPONSE_PASSWORDSENTRY._options = None
  _RETRIEVERESPONSE_PASSWORDSENTRY._serialized_options = b'8\001'
  _globals['_STOREREQUEST']._serialized_start=22
  _globals['_STOREREQUEST']._serialized_end=84
  _globals['_STORERESPONSE']._serialized_start=86
  _globals['_STORERESPONSE']._serialized_end=117
  _globals['_RETRIEVEREQUEST']._serialized_start=119
  _globals['_RETRIEVEREQUEST']._serialized_end=151
  _globals['_RETRIEVERESPONSE']._serialized_start=153
  _globals['_RETRIEVERESPONSE']._serialized_end=280
  _globals['_RETRIEVERESPONSE_PASSWORDSENTRY']._serialized_start=232
  _globals['_RETRIEVERESPONSE_PASSWORDSENTRY']._serialized_end=280
  _globals['_USERREQUEST']._serialized_start=282
  _globals['_USERREQUEST']._serialized_end=338
  _globals['_USERRESPONSE']._serialized_start=340
  _globals['_USERRESPONSE']._serialized_end=387
  _globals['_SEARCHREQUEST']._serialized_start=389
  _globals['_SEARCHREQUEST']._serialized_end=418
  _globals['_SEARCHRESPONSE']._serialized_start=420
  _globals['_SEARCHRESPONSE']._serialized_end=455
  _globals['_PASSWORDVAULT']._serialized_start=458
  _globals['_PASSWORDVAULT']._serialized_end=771
# @@protoc_insertion_point(module_scope)
